### ISSUE TITLE
Kernel stall at `native_queued_spin_lock_slowpath`

### ISSUE THREAD

**Issue by soroush** [jwbensley/EtherateMT#36]
Have you had luck with https://stackoverflow.com/questions/46267495/linux-how-to-debug-spin-lock-source ?

**Comment by jwbensley** [comment]
Hi @soroush, are you having a problem with spin locks in EtherateMT or are you asking because you wanted to know if I found an answer to that SO post?

For EtherateMT I upgraded my Kernel and the problem was gone. I get 1Mpps per core now.

What exactly are you seeing / what exactly is your issuem

**Comment by soroush** [comment]
Well I have another software which stalls on exact same symptoms. I am investigating NUMA inefficiency and kernel misconfiguration.
In case you are interested: https://serverfault.com/questions/919552/why-having-more-and-faster-cores-makes-my-multithreaded-software-slower

**Comment by jwbensley** [comment]
@soroush - Sorry for the delay I have been changing jobs.

OK seeing as you don't haven an issue with EtherateMT I will close this issue - this is not the place to discuss ServerFault questions. I will look on ServerFault and respond there.
