### ISSUE TITLE
rand() is never initialized in main()

### ISSUE THREAD

**Issue by bdemontis** [jwbensley/EtherateMT#38]
The rand() function called on line 133 will always return the same sequence, as the pseudorandom generator is never initialized. You need to insert

`srand((unsigned) time(NULL));`

before line 131.

Alternatively, insert <sys/random.h> and replace LL131-134 with:

`getrandom(eth.frm_opt.tx_buffer, eth.frm_opt.frame_sz, 0);`

**Comment by jwbensley** [comment]
Fixed in commit 8bb5b22 in dev branch

**Comment by jwbensley** [comment]
Hi @bdemontis this is fixed in the latest release, which I'm calling 1.0 because the basic features work now.

**Comment by jwbensley** [comment]
Now fixed with v1.0 release, merge #46
